### PR TITLE
refactor: use raw strings in tests

### PR DESCRIPTION
**Pull request by ZaoralJ**
## About the PR
using raw strings to in unit tests

### CODE REVIEW

**Comment by ZaoralJ** [comment]
It seems that test are platform dependant:

image

**Comment by VisualBean** [comment]
> It seems that test are platform dependant:
> 
> image

We run them both for macos and windows in the pipelines, so it really shouldn't.
We have however seen problems before with the ticks in yaml.

**Comment by VisualBean** [comment]
@ZaoralJ I just realized why I originally put the tests like they were.|
The tests are basically failing due to added whitespace.
in yaml, if a string contains a whitespace (in either end), it must be wrapped in ticks, so it doesn't get removed - which is the 'rule' we are getting into here.

**Comment by ByronMayne** [comment]
> ly failing due to added whitespace (or forbidden characters) which is probably what we are running into as its inconsistent across platforms.

The issue is not platforms but with this method. It is missing a a few edge cases as well as tests using different styles for version like strings. Some tests have `2.0.1` where others have `'2.0.1'`. In my PR I fixed all the unit tests that are failing

**Comment by VisualBean** [comment]
Hi @ZaoralJ ive done what you did, in a separate PR. Thank you though! a good change

**Pull request closed without merging**
